"""update product model

Revision ID: 403380472d78
Revises: d9a09a8e8090
Create Date: 2023-07-25 17:17:40.830068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "403380472d78"
down_revision = "d9a09a8e8090"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_product_customers", "customers", ["customer_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint("fk_product_customers", type_="foreignkey")
        batch_op.drop_column("customer_id")

    # ### end Alembic commands ###
